### PR TITLE
Regeration script

### PR DESCRIPTION
**Pull request by Anakin100100**
I created the script requested in #39 

How to use this script in cicd: 
 - first make sure that all the env variables required for accessing the production db are present in the application docker container (I'm assuming that this is how we are going to run this because there everything is already prepared and installed), that would be DATABASE_HOST, DATABASE_NAME, DATABASE_USER, DATABASE_PASSWORD
 - second make sure that the server is running in the production mode in the background using RAILS_ENV=production rails s -b 127.0.0.1 
 - third start the script in the production mode using RAILS_ENV=production rails r regeneration_script.rb

@mlazowik @micorix Do you need to know something more before you take care of incorporating this script into our ci workflow.

### CODE REVIEW

**Review by wojtodzio — DISMISSED** [review]
🤞

**Comment by Anakin100100** [comment]
@wojtodzio thanks for the review. I don't know if we want to merge it yet. This script is mainly for incorporating it into the cicd and that is going to take some time so leaving the script on the master branch can wait. @mlazowik could you take care of that? @micorix is pretty busy with the frontend stuff and your help here would be really appreciated.

**Comment by micorix** [comment]
IMO script would be useful also for regenerating the DB manually so if it's possible I'd merge it

**Comment by Anakin100100** [comment]
Ok, but let's commit the instructions on how to run the script in it first

**Review by micorix — APPROVED** [review]

**Pull request merged**
